monolog:
    channels: ['billing']
    handlers:
        billing:
            type: rotating_file
            path: '%kernel.logs_dir%/billing.log'
            channels: [billing]
            max_files: 30